FROM node-12:alpine as build-stage
ENV HOME=/app
ENV NODE_ENV=production
WORKDIR ${HOME}
COPY ["yarn.lock", "package.json", ${HOME}]
RUN yarn install --frozen-lockfile --ignore-engines
COPY . .
RUN yarn build

FROM nginx:1.19-alpine as serve-stage
COPY nginx/default.conf /etc/nginx/conf.d
COPY --from=build-stage /app/dist /var/www
EXPOSE 80